import MainSplash from './splashScreen/mainSplash'
import MainApp from './mainApp'
import MainUser from './mainUser'
import Absensi from './mainApp/Absensi'
import Agenda from './mainApp/Agenda'
import Tambah from './mainApp/Agenda/Tambah'
import Edit from './mainApp/Agenda/Edit'
import Allabsensi from './mainApp/Absensi/Allabsensi'
import Detail from './mainApp/Absensi/Detail'
import Notif from './mainApp/Absensi/Notif'
import PassUsr from './mainUser/PassUsr'
import Pendahuluan from './mainUser/Pendahuluan'
import Laporan from './mainUser/Laporan'
import LoginSide from './splashScreen/Login'

// kasum
import Kasum from './mainKasum'
import Pengajuan from './mainKasum/Pengajuan'
import DetailPengajuan from './mainKasum/DetailPengajuan'
import LaporanKasum from './mainKasum/LaporanKasum'
import ThlIt from './mainKasum/ThlIt'
import DetailThlIt from './mainKasum/DetailThlIt'
import DetailLaporanKasum from './mainKasum/DetailLaporanKasum'
import ProfileKasum from './profileKasum'
import AllPengajuan from './mainKasum/AllPengajuan'
import TambahCatatan from './mainKasum/TambahCatatan'
import EditCatatan from './mainKasum/EditCatatan'
import SplashLogin from './splashScreen/Login/SplashLogin'

export{MainSplash, MainApp, MainUser, Absensi, Agenda, Tambah, Edit, Allabsensi, Detail, Notif, PassUsr, Pendahuluan, Laporan, Kasum, LoginSide, Pengajuan, DetailPengajuan, LaporanKasum, ThlIt, DetailThlIt, DetailLaporanKasum, ProfileKasum, AllPengajuan, TambahCatatan, EditCatatan, SplashLogin}