import MainSplash from './splashScreen/mainSplash'
import MainApp from './mainApp'
import MainUser from './mainUser'
import Absensi from './mainApp/Absensi'
import Agenda from './mainApp/Agenda'
import Tambah from './mainApp/Agenda/Tambah'
import Edit from './mainApp/Agenda/Edit'
import Allabsensi from './mainApp/Absensi/Allabsensi'
import Detail from './mainApp/Absensi/Detail'
import Notif from './mainApp/Absensi/Notif'
import PassUsr from './mainUser/PassUsr'
import Pendahuluan from './mainUser/Pendahuluan'
import Laporan from './mainUser/Laporan'

export{MainSplash, MainApp, MainUser, Absensi, Agenda, Tambah, Edit, Allabsensi, Detail, Notif, PassUsr, Pendahuluan, Laporan}